var bingoList = [];
bingoList[1] = [{ name: "アマルガム", types: ["epic_spell"] },
{ name: "ブレードレイン", types: ["epic_spell"] },
{ name: "ブリザード", types: ["epic_spell"] },
{ name: "カーペットボム", types: ["epic_spell"] },
{ name: "サーキット", types: ["epic_spell"] },
{ name: "クロスタレット", types: ["epic_spell"] },
{ name: "ホショク", types: ["epic_spell"] },
{ name: "ダブルタップ", types: ["epic_spell"] },
{ name: "ファイアストーム", types: ["epic_spell"] },
{ name: "フリング", types: ["epic_spell"] },
{ name: "フォルテ", types: ["epic_spell"] },
{ name: "グレイヴ", types: ["epic_spell"] },
{ name: "ヘイルストーム", types: ["epic_spell"] },
{ name: "ヘルファイア", types: ["epic_spell"] },
{ name: "ヘルスポーション", types: ["epic_spell"] },
{ name: "アイスホッケー", types: ["epic_spell"] },
{ name: "ラストレター", types: ["epic_spell"] },
{ name: "レーザータレット", types: ["epic_spell"] },
{ name: "マイン", types: ["epic_spell"] },
{ name: "パンデミック", types: ["epic_spell"] },
{ name: "ヨゲン", types: ["epic_spell"] },
{ name: "キョウメイ", types: ["epic_spell"] },
{ name: "シャイン", types: ["epic_spell"] },
{ name: "サイドワインダー", types: ["epic_spell"] },
{ name: "スキッパー", types: ["epic_spell"] },
{ name: "スモッグ", types: ["epic_spell"] },
{ name: "スペルシールド", types: ["epic_spell"] },
{ name: "ツナミ", types: ["epic_spell"] },
{ name: "ソードオブライト", types: ["epic_spell"] },
{ name: "SDタレット", types: ["epic_spell"] },
{ name: "ヴェノショック", types: ["epic_spell"] },
{ name: "ウィルスペル", types: ["epic_spell"] },
{ name: "ワープレイ", types: ["epic_spell"] },
{ name: "ウォーターフォール", types: ["epic_spell"] },
{ name: "ワイルドファイア", types: ["epic_spell"] },
{ name: "エーテル", types: ["epic_art"] },
{ name: "炭疽菌", types: ["epic_art"] },
{ name: "ローラーブレード", types: ["epic_art"] },
{ name: "キャンディラッパー", types: ["epic_art"] },
{ name: "コールドプレスジュース", types: ["epic_art"] },
{ name: "ラッパズイセン", types: ["epic_art"] },
{ name: "エリュシオン", types: ["epic_art"] },
{ name: "ジャイアントアーマー", types: ["epic_art"] },
{ name: "グリップテープ", types: ["epic_art"] },
{ name: "免疫システム", types: ["epic_art"] },
{ name: "モルテンコア", types: ["epic_art"] },
{ name: "ペット：キツネ", types: ["epic_art"] },
{ name: "ペット：カメ", types: ["epic_art"] },
{ name: "懐中時計", types: ["epic_art"] },
{ name: "サイゴンアーマー", types: ["epic_art"] },
{ name: "盗人免許", types: ["epic_art"] },
{ name: "ステップドローン", types: ["epic_art"] },
{ name: "トライフロスト", types: ["epic_art"] }];
bingoList[2] = [{ name: "a", types: [""] }];
bingoList[3] = [{ name: "お金2000以上所持", types: ["money"] },
{ name: "アンビエントバースト", types: ["rare"] },
{ name: "ブースターショット", types: ["rare"] },
{ name: "ブレイクアウト", types: ["rare"] },
{ name: "テツビシ", types: ["rare"] },
{ name: "フェードアウェイ", types: ["rare"] },
{ name: "キュウソク", types: ["rare"] },
{ name: "サルベージ", types: ["rare"] },
{ name: "サンダーストーム", types: ["rare"] },
{ name: "ワブル", types: ["rare"] },
{ name: "スウィーパー", types: ["rare"] },
{ name: "トラクタービーム", types: ["rare"] },
{ name: "リバースウェイブ", types: ["rare"] }];
bingoList[4] = [{ name: "素のマナ再生速度1.5以上", types: ["managen"] },
{ name: "幸運77以上", types: ["luck"] },
{ name: "MAXHP2100以上", types: ["maxhp"] },
{ name: "クロスファイアX", types: ["rein"] },
{ name: "クナイK", types: ["rein"] },
{ name: "シャードトスB", types: ["rein"] },
{ name: "メイソウT", types: ["rein"] },
{ name: "アヌビスQ", types: ["rein"] },
{ name: "シールドアップU", types: ["rein"] },
{ name: "スペル強化Z", types: ["rein"] }];
bingoList[5] = [{ name: "スサノオノカゴ", types: ["legend_spell"] },
{ name: "ブラッドシールド", types: ["legend_spell"] },
{ name: "ジョウヘキ", types: ["legend_spell"] },
{ name: "ギャンビット", types: ["legend_spell"] },
{ name: "グリッターボム", types: ["legend_spell"] },
{ name: "グリッターストーム", types: ["legend_spell"] },
{ name: "セイハイ", types: ["legend_spell"] },
{ name: "ギロチン", types: ["legend_spell"] },
{ name: "アイスシールド", types: ["legend_spell"] },
{ name: "インフィニティビーム", types: ["legend_spell"] },
{ name: "モニュメント", types: ["legend_spell"] },
{ name: "ソーラーチャージ", types: ["legend_spell"] },
{ name: "スピリットソード", types: ["legend_spell"] },
{ name: "ステイシス", types: ["legend_spell"] },
{ name: "サステイン", types: ["legend_spell"] },
{ name: "タイムストップ", types: ["legend_spell"] },
{ name: "マナバースト", types: ["legend_spell"] },
{ name: "ヴィヴィセクション", types: ["legend_spell"] },
{ name: "ヤドクガエル", types: ["legend_art"] },
{ name: "フリーザーバーン", types: ["legend_art"] },
{ name: "フロストメイル", types: ["legend_art"] },
{ name: "ハートオブゴールド", types: ["legend_art"] },
{ name: "ライラック", types: ["legend_art"] },
{ name: "ミョルニル", types: ["legend_art"] },
{ name: "マザー", types: ["legend_art"] },
{ name: "ペット：ライガー", types: ["legend_art"] },
{ name: "フェイズプレート", types: ["legend_art"] },
{ name: "タイトパンツ", types: ["legend_art"] },
{ name: "ティンダー", types: ["legend_art"] },
{ name: "トランセンデンス", types: ["legend_art"] },
{ name: "ユニコーンボム", types: ["legend_art"] },
{ name: "Vガン", types: ["legend_art"] },
{ name: "ウイング", types: ["legend_art"] },
{ name: "お金77", types: ["money"] },
{ name: "お金131", types: ["money"] },
{ name: "お金222", types: ["money"] },
{ name: "デッキ画面でカード総数33以上", types: ["card"] }];
bingoList[6] = [{ name: "興奮剤なしでMAXマナ11以上", types: ["maxmana"] },
{ name: "削除13個所持", types: ["delete"] }];
bingoList[7] = [{ name: "防御力-201以下", types: ["defence"] },
{ name: "フロー50以上", types: ["flow"] },
{ name: "戦闘中にSP+13以上", types: ["spellpower"] },
{ name: "コイントスで200失う", types: ["luck"] },
{ name: "コイントスで200得る", types: ["luck"] },
{ name: "同じ強化2連続", types: ["rein"] }];
bingoList[8] = [{ name: "お金365", types: ["money"] },
{ name: "ボスと相打ち", types: ["boss"] },
{ name: "ソウルファイア160ダメージ以上", types: ["rein"] }];
bingoList[9] = [{ name: "s", types: [""] }];
bingoList[10] = [{ name: "ブレードスクリーム", types: ["calamity_spell"] },
{ name: "サイネット", types: ["calamity_spell"] },
{ name: "エクスカリバー", types: ["calamity_spell"] },
{ name: "エクスプロージョン", types: ["calamity_spell"] },
{ name: "フューリー", types: ["calamity_spell"] },
{ name: "ライフソード", types: ["calamity_spell"] },
{ name: "ミッドナイト", types: ["calamity_spell"] },
{ name: "モンスーン", types: ["calamity_spell"] },
{ name: "イクサノミチ", types: ["calamity_spell"] }];
bingoList[11] = [{ name: "契約13個同時所持", types: ["pact"] }];
bingoList[12] = [{ name: "花を4つ集める", types: ["collect"] },
{ name: "指輪を5つ集める", types: ["collect"] },
{ name: "宝石を3つ集める", types: ["collect"] }];
bingoList[13] = [{ name: "お金666", types: ["money"] },
{ name: "お金777", types: ["money"] },
{ name: "お金999", types: ["money"] },
{ name: "コスト9以上のスペル所持", types: ["rein"] },
{ name: "コスト8のスペル所持", types: ["rein"] },
{ name: "Nルート13分台クリア", types: ["clear"] },
{ name: "Pルート13分台クリア", types: ["clear"] }];
bingoList[14] = [{ name: "スペル強化6段階", types: ["rein"] }];
bingoList[15] = [{ name: "Gルート15分台クリア", types: ["clear"] }];
bingoList[16] = [{ name: "d", types: [""] }];
bingoList[17] = [{ name: "f", types: [""] }];
bingoList[18] = [{ name: "g", types: [""] }];
bingoList[19] = [{ name: "h", types: [""] }];
bingoList[20] = [{ name: "j", types: [""] }];
bingoList[21] = [{ name: "カラミティスペル7種類", types: ["calamity"] }];
bingoList[22] = [{ name: "k", types: [""] }];
bingoList[23] = [{ name: "l", types: [""] }];
bingoList[24] = [{ name: "m", types: [""] }];
bingoList[25] = [{ name: "Nルートでセリフ倒す", types: ["hell"] }];

$(function() { srl.bingo(bingoList, 5); });